version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "07:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: io.vertx:vertx-stack-depchain
    versions:
    - 4.0.0
    - 4.0.1
    - 4.0.2
  - dependency-name: io.reactiverse:vertx-maven-plugin
    versions:
    - 1.0.23
